### ISSUE TITLE
Are the pins on the LILYGO Paxcounter LoRa v2.1_1 broken out in such a way that sensors can be used?

### ISSUE THREAD

**Issue by proffalken** [cyberman54/ESP32-Paxcounter#1000]
I've got an old TT-GO T-Beam and a few Heltec WiFi LoRa32 boards and one of the issues I'm having is that we want to hook up both an SDS011 and a BME680 to the Paxcounter at the same time but on these boards many of the pins that are broken out to the headers are actually used for other things already, so you have to turn the screen off etc.

I'd love to get the LILYGO Paxcounter as the main hardware module, but I can't see anything in the specs about whether external sensors are supported on this model.

If they are, then that's awesome and I'll pick up a few along with the various sensors.  If they're not, I'd love recommendations for modules that *can* support this configuration.

Thanks in advance!

**Comment by cyberman54** [comment]
You can use any free GPIO pin of Lora v2.1.board to connect multiple external sensors. Or you can have multiple sensors on the same i2c interface. Look in generic.h for examples. Copy sensor definitions as needed to your lora v2.1 hal file.
