### ISSUE TITLE
MAC Address Randomization

### ISSUE THREAD

**Issue by Timmwardion** [cyberman54/ESP32-Paxcounter#1006]
How does Pax Counter deal with MAC address randomization. To get accurate readings of people/devices MAC addresses are now pretty much useless as devices will generally change reported MAC addresses for every request to APs where they are not authenticated.

At least that's my understanding.

**Comment by cyberman54** [comment]
Pax Counter intentionally does count local ("randomized") MACs only.

**Comment by Timmwardion** [comment]
Ok, thanks. So it’s overcounting then. That is, it doesn’t count people or devices, it counts Mac addresses (and each device will have many of them reported).
