### ISSUE TITLE
can't compile for TTGO V.2.1, mac, atom

### ISSUE THREAD

**Issue by sbamueller** [cyberman54/ESP32-Paxcounter#102]
So we installed platform.io on atom, configured to ttgo v2.1.
When building using the platform.io plugin we get the following error message: 

`src/blecsan.cpp:15:22: fatal error: bt_types.h: No such file or directory`

what should we do?

**Comment by sbamueller** [comment]
doesn't work on archlinux either

**Comment by cyberman54** [comment]
The <bt_types.h> lib is no longer needed, BLE ADDR TYPE now coming from <esp_blufi_api.h>.
In branch master I removed the #include statement which caused the compile error.
So it should work now.
