### ISSUE TITLE
Can I use 2 Separate Antenna For Wi-Fi and LoRa.

### ISSUE THREAD

**Issue by Rajukumardeo** [cyberman54/ESP32-Paxcounter#1024]
I want to receive Wi-Fi signal and same received signal i want to forward through the LoRa continuously and real time, so i need the separate antenna for Wi-Fi and LoRa, is it possible.?

**Comment by cyberman54** [comment]
You always need separate antennas for Wifi and LoRa, since these are separated radios using different frequencies.
