### ISSUE TITLE
src/macsniff.cpp:15:75

### ISSUE THREAD

**Issue by sbamueller** [cyberman54/ESP32-Paxcounter#103]
<img width="822" alt="grafik" src="https://user-images.githubusercontent.com/24292608/42217638-46968302-7ec6-11e8-8188-534119261ecb.png">

Now I get this issue

**Comment by cyberman54** [comment]
On MS VSC with PlatformIO core this compiles without error.
I can't solve this, we need some C/C++ expert here.

**Comment by sbamueller** [comment]
The information system student next to me says your are doing fancy shit which could be replaced by simpler code.

Alternative does it work on Microsoft Windows?

**Comment by cyberman54** [comment]
If he or you can do better, make pull request.

Meanwhile i fixed Espressif Platform to 1.0.2, perhaps you used a newer one.
Try again to compile after syncing master.

**Comment by cyberman54** [comment]
Workaround by fixing Espressif32 core to v1.0.2 works.
Problem occurs after update Espressif32 core to v1.1.0.

**Comment by cyberman54** [comment]
solved in v1.8.83 (currently available only on branch development)
