### ISSUE TITLE
counter can become negativ

### ISSUE THREAD

**Issue by SchneHa** [cyberman54/ESP32-Paxcounter#117]
I found another issue regarding the "*100 bug" (Cayenne LPP payload):
If count is set to 1 (continuous counting without reset of the counter), the counter can become negativ. In display it is shown correctly but Cayenne payload is wrong. It's the same for WiFi and BLE counting.

**Comment by cyberman54** [comment]
fixed.

**Comment by SchneHa** [comment]
I tested and the issue persists.
