### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Milbrot** [cyberman54/ESP32-Paxcounter#138]
Since version 1.4.2 there is a build error if PAYLOAD_ENCODER value in paxcounter.conf  is 3 
Error message then:

Compiling .pioenvs\ttgov21\src\rcommand.cpp.o
src\payload.cpp: In member function 'void PayloadConvert::addAlarm(int8_t, uint8_t)':
src\payload.cpp:231:22: error: 'LPP_PRESENCE' was not declared in this scope
buffer[cursor++] = LPP_PRESENCE;
^
*** [.pioenvs\ttgov21\src\payload.cpp.o] Error 1

**Comment by cyberman54** [comment]
Fixed.
Thanks for reporting this bug.
