### ISSUE TITLE
Count passengers via serial monitor

### ISSUE THREAD

**Issue by provotector** [cyberman54/ESP32-Paxcounter#146]
Hello. I'm using ESP32 dev board. I need to test if the software is counting in the simplest way possible.

If I no have Lora or Screen attached I can see the metered counts via serial monitor? how? I can usea regular 8x2 i2c LCD instead using OLED? how can define the screen type? Thank you for the help!!

**Comment by gregorwolf** [comment]
Have you found a way how to do that?

**Comment by cyberman54** [comment]
Just enable debug mode level "debug = 4" in platformio.ini in [common] section.
Then you see all counts on serial console.
