### ISSUE TITLE
Changing paxcounter.conf have no effet

### ISSUE THREAD

**Issue by disk91** [cyberman54/ESP32-Paxcounter#147]
I've tried to changed the wifi scanning timing and send timing to use larger windows. I made a Clean / Build / Upload but the timing are still the default one.
What do I miss ?
Sincerely,
Paul

**Comment by cyberman54** [comment]
@disk91 Intention of the parameters in paxcounter.conf is to have a default initial configuration here. Changing the parameters should be done during runtime via remote command (see rcommand.cpp), not by rebuilding the software.

**Comment by cyberman54** [comment]
PROGVERSION now moved from paxcounter.conf to platformio.ini
