### ISSUE TITLE
Update vendor_array.h to newer OUI list

### ISSUE THREAD

**Issue by spmrider** [cyberman54/ESP32-Paxcounter#150]
An updated version of vendor_array.h has been created, it is available at [https://service.rules.org/owncloud/index.php/s/QQZN4eK3o3Zf3xu](url)

This version adds one vendor (Caterpillar, on special request) as well as updates the list with new prefixes for all other vendors

**Comment by cyberman54** [comment]
Done.

**Comment by spmrider** [comment]
Since last Update the vendor list changed again, I'll put up an updated version.

**Comment by spmrider** [comment]
Done (committed to master)

**Comment by spmrider** [comment]
New vendor_array.h has been committed to development branch

**Comment by cyberman54** [comment]
Can we add toolchain to create vendor_array.h to the repository? (license, ... )

**Comment by spmrider** [comment]
I just ported the toolchain from FreeBSD to Linux, needs some cleanup, will 
add it shortly to a tools folder

Am 7. August 2019 21:03:47 schrieb Verkehrsrot <notifications@github.com>:

**Comment by cyberman54** [comment]
Continued in https://github.com/cyberman54/ESP32-Paxcounter/issues/675
