### ISSUE TITLE
Enhancement - Make OTA update selectable

### ISSUE THREAD

**Issue by Bingo600** [cyberman54/ESP32-Paxcounter#163]
[USE_OTA.diff.tar.gz](https://github.com/cyberman54/ESP32-Paxcounter/files/2408584/USE_OTA.diff.tar.gz)

Short "diff" to enable/disable OTA Update  - Not tested on real hw yet

**Comment by cyberman54** [comment]
How can i use your diff file with PlatformIO on VScode for Windows?

**Comment by cyberman54** [comment]
@Bingo600 Please make Pull Request.

**Comment by cyberman54** [comment]
Done in v1.5.6 (see development branch)
