### ISSUE TITLE
Metered counts to local SPI

### ISSUE THREAD

**Issue by prolland56000** [cyberman54/ESP32-Paxcounter#165]
Dear,
it seem that metered counts can be  transferred to a server via a LoRaWAN network, and a local SPI cable interface. 
My question is : if SPI data can be read by ICSP pin on arduino Uno board ?
Best regards.

**Comment by der-ambi** [comment]
This is work in progress, see #109

**Comment by cyberman54** [comment]
I close this issue, since it's the same as #109
