### ISSUE TITLE
Change LMIC to lmic esp32 port

### ISSUE THREAD

**Issue by cyberman54** [cyberman54/ESP32-Paxcounter#171]
using [this lmic port f](https://github.com/ngraziano/lmicesp32)or esp32:

- persists LoRaWAN keys in RTC NVRAM
- uses ESP32 hardware AES acceleration

or using these maybe better maintained? ports:

https://github.com/mcci-catena/arduino-lorawan

https://github.com/manuelbl/ttn-esp32

**Comment by mutton74** [comment]
It would great to use this fork to allow for different band plans easily, having trouble using this code on AU915 at the moment
https://github.com/mcci-catena/arduino-lmic

**Comment by hagenbuch** [comment]
Isnt the RTC RAM erased with every reset?

**Comment by cyberman54** [comment]
Depends on kind of reset, RTC does not survive power cycle, we need NVS RAM for that.
Take a look here: https://www.esp32.com/viewtopic.php?t=4931

**Comment by cyberman54** [comment]
Done with v1.6.5, code migrated to [LMIC 1.6 arduino port by MCCI](https://github.com/mcci-catena/arduino-lmic)

@mutton74 : you find this version currently in the development branch - could you please test it?
