### ISSUE TITLE
Beacon proximity alarm mode

### ISSUE THREAD

**Issue by jwende** [cyberman54/ESP32-Paxcounter#194]
According to the readme the device configuration query result should contain the 'Beacon proximity alarm mode' at byte 17 - but there is no entry in the source code (PayloadConvert::addConfig).

just for my understanding  ....
J.

**Comment by cyberman54** [comment]
https://github.com/cyberman54/ESP32-Paxcounter/blob/master/src/payload.cpp#L29

**Comment by cyberman54** [comment]
Yes, this is missing, it's a bug.

**Comment by cyberman54** [comment]
Fixed with v1.6.54 (currently in development branch)
