### ISSUE TITLE
TTGO Beam stopps sending after join and one message

### ISSUE THREAD

**Issue by sbamueller** [cyberman54/ESP32-Paxcounter#222]
![grafik](https://user-images.githubusercontent.com/24292608/50058873-06ea3f00-017f-11e9-9852-8e51046fed42.png)
![grafik](https://user-images.githubusercontent.com/24292608/50058878-16698800-017f-11e9-8ca3-767c4055e673.png)
I flashed the TTGO Beam. When I power it up it produces a join and then sends one message with BLE/WIFI. Then the device stops sending. No matter if I send 0301 or any other message. It stopps sending. I'm not sure what I can do anymore. 
I have spoken with Bahnhofsoma (https://twitter.com/Bahnhofsoma/status/1074008037600452608) and also with a guy at TTN Stuttgart Meeting who both have the same problem.

**Comment by cyberman54** [comment]
Please increase debug level to 4 in platformio.ini, then flash again and monitor output on serial console. Please post output here.

**Comment by cyberman54** [comment]
try changing version in platformio.ini from 1.6.971 to 1.6.972, reflash and report the result here.

**Comment by cyberman54** [comment]
@sbamueller ask the supplier.
"T22_V07" is probably the newer version. So try ttgobeam_new.h

**Comment by cyberman54** [comment]
Thanks, so it close this issue.
If problems persist, please re-open this issue.

**Comment by sbamueller** [comment]
Tjakkaaaaa works
