### ISSUE TITLE
bug in plain decoder for: GPS

### ISSUE THREAD

**Issue by sbamueller** [cyberman54/ESP32-Paxcounter#224]
There seems to be a bug in the plain payload decoder.

`if (port === 1) {
    var i = 0;

    decoded.wifi = (bytes[i++] << 8) | bytes[i++];
    decoded.ble = (bytes[i++] << 8) | bytes[i++];

    if (bytes.length > 4) {
      decoded.latitude = ((bytes[i++] << 24) | (bytes[i++] << 16) | (bytes[i++] << 8) | bytes[i++]);
      decoded.longitude = ((bytes[i++] << 24) | (bytes[i++] << 16) | (bytes[i++] << 8) | bytes[i++]);
      decoded.sats = bytes[i++];
      decoded.hdop = (bytes[i++] << 8) | (bytes[i++]);
      decoded.altitude = (bytes[i++] << 8) | (bytes[i++]);
    }
}`

But according to the documentation, the location is send by the device on port "Port #4: GPS data"
So shouldn't there a if (port === 4) {
  }

aroudn the the second part?

I tried fixing, by entering but it messes up my stuff

**Comment by cyberman54** [comment]
Fixed this by adding a port 4 evaluation statement.
Keeping GPS data evaluation also on port 1 to ensure backward compatibility for devices running previous software versions.
