### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by qvs5010** [cyberman54/ESP32-Paxcounter#226]
Hi

I want to ask, how can i connect a external button.

I want to connect the following button.

[https://images-na.ssl-images-amazon.com/images/I/61Tv47rW6cL._SX679_.jpg](https://images-na.ssl-images-amazon.com/images/I/61Tv47rW6cL._SX679_.jpg)

It has 2 wires, so my understanding is, i can connect one wire to GND (Ground) and the other to a GIOP Pin 22?

And then just change the GIOP ping in the ESP32-Paxcounter/src/hal/ttgobeam.h from 

`#define HAS_BUTTON GPIO_NUM_39 // on board button "BOOT" (next to reset button)`

to

`#define HAS_BUTTON GPIO_NUM_22 // on board button "BOOT" (next to reset button)`

But do i need to connect VCC anywhere, and do i have to use a resistor and how big if i need to?

Thanks
Q

**Comment by cyberman54** [comment]
It should work this simple way
 Have in mind that you have no button debouncing this way, but can be done by software if.needed.

**Comment by qvs5010** [comment]
Hi Cyberman

Thanks

But must i connect the VCC with a resistor?

like the following.

[https://lastminuteengineers.com/wp-content/uploads/2018/11/Connecting-Button-to-ESP32-for-ext0-External-Wakeup-Source.png](https://lastminuteengineers.com/wp-content/uploads/2018/11/Connecting-Button-to-ESP32-for-ext0-External-Wakeup-Source.png)

**Comment by cyberman54** [comment]
No.

**Comment by qvs5010** [comment]
Aaaa cool, so it just GIOP 22 to Ground.

Thanks
