### ISSUE TITLE
Fix BLECOUNTER logic in main.cpp

### ISSUE THREAD

**Issue by spmrider** [cyberman54/ESP32-Paxcounter#249]
In main.cpp in an #ifdef BLECOUNTER / #else / #endif block (around line 200). When trying to disable BLE completely (by removing the BLECOUNTER define in paxcounter.conf) I get compile time errors due to unknown symbols. Also the logic is completely clear to me.

My suggestion is to remove the #else as well as the following lines up to (but not including?) the esp_coex_preference_set

This would enable compiling with or without BT/BLE stack again.

Any objections?

**Comment by cyberman54** [comment]
Fixed by sanitizing some includes.

Even without BLECOUNTER function we need the esp BT libs to remove the BT/BLE stack during runtime. This increases free heap memory.

**Comment by spmrider** [comment]
It compiles but (for not further determined reasons) the device init does not work. At the moment I can't debug, but let's keep the issue open, until I get this done. We may consider to remove the BLECOUNTER #define then completely, however, code size changes quite a bit.

**Comment by cyberman54** [comment]
HAS_BME seletcs feature BT/BLE stack at compile time, at expense of flash memory.

BLECOUNTER selects default state of shutting down BT/BLE stack during device startup at expense of heap memory.

**Comment by cyberman54** [comment]
solved.
