### ISSUE TITLE
Style: replace #ifdef FOO by #if(FOO)

### ISSUE THREAD

**Issue by spmrider** [cyberman54/ESP32-Paxcounter#250]
I suggest to replace occurences of #ifdef FOO for all boolean checks by #if(FOO)

This enables to switch features by defining a value true or false (1 or 0 if you prefer), but would still be compatible with the current comment in/out way of configuring things. The master #define FOO could also be surrounded by #ifndef FOO - this would open the config logic to a local config file that either sets some values with compile option or a local config (gitignore'd) config.

Better ideas?

**Comment by cyberman54** [comment]
@spmrider Please create new branch based on current development branch to try this.

**Comment by spmrider** [comment]
In branch ifdef-dev I replaced several #ifdev / #if defined by #if(...)
Before opening the pull request could someone else check and test, please?

**Comment by cyberman54** [comment]
Merged with branch development, no compile issues so far.

**Comment by cyberman54** [comment]
done.
