### ISSUE TITLE
ttgo beam with sds 011

### ISSUE THREAD

**Issue by sbamueller** [cyberman54/ESP32-Paxcounter#276]
my ttgo beam does not transmit any gps data.
what could be the cause?

<img width="1027" alt="grafik" src="https://user-images.githubusercontent.com/24292608/53123836-4d329480-355a-11e9-99d5-f79f7a499f6e.png">

**Comment by cyberman54** [comment]
Probably one of these reasons:

- Your GPS has no fix, thus has not yet sent any NMEA record with valid(!) location data
- You did not configure GPS or you set erraneous parameters for the GPS interface (serial params / i2c addr) -> in <board>.h file
- GPS interface hardware not working -> check wiring
- GPS data transmit was switched off before and saved to NVRAM, thus reloaded at reboot -> rcommand 0x03
- You have setup an active payload decoder/converter in TTN console which filters the data

**Comment by cyberman54** [comment]
Ok, got it: with one of last commits GPS was disabled by default in `ttgobeam.h` file, i changed it. Please update ttgobeam.h and reflash.
