### ISSUE TITLE
How do I add a "custom sensor" to PaxCounter

### ISSUE THREAD

**Issue by proffalken** [cyberman54/ESP32-Paxcounter#329]
Hello,

The README suggests that I can add extra sensors to the PAXCounter code by editing a file called "sensors.cpp", however this file does not exist in the source.

Do I need to create this file? And if so, is there an example somewhere of what the content should look like?

**Comment by cyberman54** [comment]
The file is already there, the link in the readme.md was broken.
I corrected it.
Please have a look in src/sensor.cpp how to add a custom sensor.
