### ISSUE TITLE
src/lorawan.cpp:507:48: error: too many arguments to function 'void adjustTime(long int)'

### ISSUE THREAD

**Issue by clandeck** [cyberman54/ESP32-Paxcounter#332]
I tried it with Platform IO on Atom and VSC and get

src/lorawan.cpp: In function 'void user_request_network_time_callback(void*, int)':
src/lorawan.cpp:507:48: error: too many arguments to function 'void adjustTime(long int)'
adjustTime(*pUserUTCTime + requestDelaySec, 0);

while compiling on a Mojave 10.14.4 OSX.

The files I modified are.
platformio.ini for Heltec v2 board
loraconf.h with UUIDs
ota.conf
paxcounter.conf #define TIME_SYNC_INTERVAL              60   
lmic_conf.h

**Comment by cyberman54** [comment]
fixed.
