### ISSUE TITLE
Problem TTG T-BEAM with BME280

### ISSUE THREAD

**Issue by heydemar** [cyberman54/ESP32-Paxcounter#340]
Hi, 

can anybody explain to me what I have to do to run the BME230 at my T-BEAM? 
In the Console of TTN I have only this: 

17:55:10367payload:0000000000000000air:0humidity:0pressure:0temperature:0

I have wired on Pin GND + 3V + 22(SCL) + 21(SDA)

Thanks!

In the ttgobeam.h I have this lines: 
// enable only if device has these sensors, otherwise comment these lines
// BME680 sensor on I2C bus
#define HAS_BME 1 // Enable BME sensors in general
//#define HAS_BME680 SDA, SCL
//#define BME680_ADDR BME680_I2C_ADDR_PRIMARY // !! connect SDIO of BME680 to GND !!

In the platform.ini this lines
env:ttgobeam]
platform = ${common.platform_espressif32}
framework = arduino
board = ttgo-t-beam
board_build.partitions = ${common.board_build.partitions}
upload_speed = 921600
;upload_port = /dev/ttyUSB1
;COM1 or COM3
;upload_port = COM[3]
lib_deps =
    ${common.lib_deps_basic}
    ${common.lib_deps_lora}
    ${common.lib_deps_gps}
    ${common.lib_deps_display}
lib_deps_sensors =
    ;Adafruit Unified Sensor@^1.0.3
    Adafruit BME280 Library@1.0.8
build_flags =
    ${common.build_flags_all}
    -mfix-esp32-psram-cache-issue
upload_protocol = ${common.upload_protocol}
extra_scripts = ${common.extra_scripts}
monitor_speed = ${common.monitor_speed}

**Comment by cyberman54** [comment]
If you have BME280, not BME680, you need to define HAS_BME280, not 680. look in generic.h and find the example there.

**Comment by cyberman54** [comment]
See PR #343 

https://github.com/cyberman54/ESP32-Paxcounter/pull/343/
