### ISSUE TITLE
Proximity Payload not sending?

### ISSUE THREAD

**Issue by Zufallsfuchs** [cyberman54/ESP32-Paxcounter#342]
We've enabled the beacon alarm function via remote command  0x11 0x01
And set the MAC to the address of a smartphone we used for testing via rcommand 0x12 01 ...

But sill we don't receive any responses concerning proximity in TTN nor in the serial monitor.

We are using the packed_decoder.js and the packed_converter.js available in the repo.

Are we missing a step or is there some problem with the code?

**Comment by simzik** [comment]
Same Problem on my side. I also use an ESP8266 to constantly send Beacons every Second. But i do not get a beacon alarm.

**Comment by cyberman54** [comment]
Did you use Wifi oder Bluetooth clients/beacons?

**Comment by simzik** [comment]
I use wifi from the esp8266

**Comment by cyberman54** [comment]
Sure this is possible. The OUI filter currently is applied before beacon match is processed (see macsniff.cpp). To ensure you MAC is not OUI filtered, compile the code without Vendorfilter.

**Comment by cyberman54** [comment]
Fixed.

https://github.com/cyberman54/ESP32-Paxcounter/pull/475
