### ISSUE TITLE
Lopy gets no connection over LoRaWAN

### ISSUE THREAD

**Issue by kami83** [cyberman54/ESP32-Paxcounter#360]
Hi,

i am try to connect my Lopy to TheThingNetwork. But i get no connection. If i try to reduce the LORALevel to 9 or 7 i always get this message when i reboot:

[I][configmanager.cpp:222] loadConfig(): lorasf = 12

Is this right?

Thanks a lot.

Cu kami83

**Comment by cyberman54** [comment]
If you change parameters in configmanager.cpp to persist them, you either need to clear NVS before, or change version number, as explained [here](https://github.com/cyberman54/ESP32-Paxcounter/issues/272)
