### ISSUE TITLE
Pin mapping not correct for Heltec LoRa 32 V2 868MHz

### ISSUE THREAD

**Issue by ssozonoff** [cyberman54/ESP32-Paxcounter#363]
Had to change as follows in heltecv2.h file else you wont get a complete event for the lora sends.

#define LORA_IRQ 26
#define LORA_IO1 35
#define LORA_IO2 34

**Comment by cyberman54** [comment]
fixed this in platformio.ini 
https://github.com/cyberman54/ESP32-Paxcounter/commit/6796d65
