### ISSUE TITLE
Timesync protocol: LoRa transfer time is not considered

### ISSUE THREAD

**Issue by cyberman54** [cyberman54/ESP32-Paxcounter#370]
`process_timesync_req()` in `timesync.cpp` does not consider transmit airtime of the timesync packet. Not sure if this should be considered. If yes, we need to check LoRa SF for the timesync packet and convert SF to milliseconds air time delay.

**Comment by FlorianLudwig** [comment]
As long as the time on the gateway and on the node is taken on the same time (both at the start or at the end of the frame) the airtime does is not part of the calculation.

In the implementations I know of the gateway timestamps packages at the end of the transmission, so does the current node implementation.  Therefor the airtime is not part of the calculation.

**Comment by cyberman54** [comment]
Ok, so this seems not to be a source of erraneous timesyncs.
Thanks.
