### ISSUE TITLE
Problem when compiling TTG T-BEAM

### ISSUE THREAD

**Issue by Tomtendo** [cyberman54/ESP32-Paxcounter#373]
Hi Folks,

when trying to compile the Paxcounter i always get this Message: 

.piolibdeps/MCCI LoRaWAN LMIC library/src/lmic/lmic_config_preconditions.h:92:52: fatal error: ../../../../../src/lmic_config.h: No such file or directory

Thanks for the Help!

**Comment by cyberman54** [comment]
Read the hints in platformio.ini regarding the platformio version and select appropriate path, or update your platformio version.

Unfortunately this is a platformio problem which came up with last platformio update.

**Comment by shenzou** [comment]
Hi @Tomtendo ,
I had the same problem, check that your platformio version is not under 4.0.0a15. If it is, uncomment the following line:
'-DARDUINO_LMIC_PROJECT_CONFIG_H=../../../src/lmic_config.h'
and comment the following line:
'-DARDUINO_LMIC_PROJECT_CONFIG_H=../../../../../src/lmic_config.h'
in the platformio.ini file, as explained on it.

**Comment by cyberman54** [comment]
@shenzou @Tomtendo I found a way to avoid this, regardless of platformio version. Is currently coded in branch development. Could you, please, re-test with the development branch, and report results here? Thanks.

Please note your environment: operating system (Windows / Linux) and editor (Atom / VSC). Thanks.

**Comment by Tomtendo** [comment]
It worked for me by using an old Platformio Version, thank you guys for the quick help.

**Comment by cyberman54** [comment]
Solved.
