### ISSUE TITLE
Question concerning WiFi / Voltage Messages

### ISSUE THREAD

**Issue by shinebar1001** [cyberman54/ESP32-Paxcounter#374]
Thank you for your great work. I've got a question concerning the sending of the messages. When the vendor filter is activated, paxcounter is sending "voltage" message on port 8 quite often and messages with counted WiFi-Devices don't get transmitted. Is there a way to supress the voltage-messages? Am I doing something wrong?
best regards
Danny

![image](https://user-images.githubusercontent.com/33186930/58434383-af4fe800-80bb-11e9-9205-118af0982611.png)

**Comment by shinebar1001** [comment]
Question answered: I removed the definition of the battery capabilities from the HAL. But as I use the TTGO 2.1 V 1.6 USB-powered there must be something wrong with the internal divider - any suggestions on making this slightly more configurable?

**Comment by cyberman54** [comment]
@shinebar1001 If you plug USB you cannot measure battery voltage on the TTGO.

**Comment by shinebar1001** [comment]
Yep, of course - but out of the box paxcounter tried to do that. I noticed a picture where "USB" was displayed - am I doing something wrong? Otherwise I'd try to submit a PR which makes this configurable

**Comment by cyberman54** [comment]
Please make PR, thanks.

**Comment by shinebar1001** [comment]
Got an idea already, will take some time as I only got one device which is currently in the office.

**Comment by cyberman54** [comment]
@shinebar1001 
Maybe you can solve issue #321 with your PR, too?

Please have in mind that on some boards there is a Vext on/off switch, e.g. EcoPower, HeltecV2 and TTGP v1.6

I found out that setting of Vext on/off switch may or must be considered when it comes to measure voltage of battery. Depending on schematic of boards.

**Comment by shinebar1001** [comment]
That seems possible, I just ordered a HeltecV2
