### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by ASLABSIT** [cyberman54/ESP32-Paxcounter#381]
Hello, I just download and compiling with PlatformIO (VSCODE) and i get the errors in the attaced txt: 

[platformio.txt](https://github.com/cyberman54/ESP32-Paxcounter/files/3269780/platformio.txt)

PlatformIO verision Home 2.1.0 Core 3.6.7

I try to solve by myself :
1 DIO0... error removing temporarily the definition an put hardcode.
2 types.h  ( read somewere that it seems no more necessary )
3 NOT SOLVED

in the attaced txt file the resul of the  compilations
-FIST COMPILE ( remove DIO0... definition )
-SECOND COMPILE ( remove types.h )
-THIRD COMPILE (?? *** [.pioenvs\heltec_wifi_lora_32\src\macsniff.cpp.o] Error 1 ??)

**Comment by cyberman54** [comment]
This looks like you're using an outdated, very old, version of this repository, since "monitor_baud" was deleted from platformio.ini some time ago.
Please make sure you have a recent github fork, the try again.
If issue persits, please re-open this issue.
