### ISSUE TITLE
About src/paxcounter.conf

### ISSUE THREAD

**Issue by uceekji** [cyberman54/ESP32-Paxcounter#410]
I am the new one who use platformio. The loraWAN antenna I used is 868MHz. The board I used is TTGO-T-Beam. The temperature sensor I used is BME280. What and how can I changed something in paxcounter.conf as what I need?

Thank you

**Comment by cyberman54** [comment]
This is an issue tracker, not a support forum. Please read the tutorial, as linked at top of the README. Then if something does not work as described, you may open issue here.
