### ISSUE TITLE
 Error - UnconfirmedDataUp - Loraserver.io

### ISSUE THREAD

**Issue by viniaero** [cyberman54/ESP32-Paxcounter#428]
Hello,
I can not receive the data, I set 3 = Cayenne LPP dynamic. but it doesn't work

![image](https://user-images.githubusercontent.com/2416508/64480482-bef0c980-d19e-11e9-820e-895604a94d0a.png)

![image](https://user-images.githubusercontent.com/2416508/64480462-5dc8f600-d19e-11e9-8826-e9830355dd9e.png)

![image](https://user-images.githubusercontent.com/2416508/64480485-df208880-d19e-11e9-944d-bd198a11f278.png)

What can I do wrong?

**Comment by cyberman54** [comment]
Probably you have issues with your setup. Try TTN.

**Comment by viniaero** [comment]
I just tested on TTN, is it working, what can it be?

**Comment by cyberman54** [comment]
This is not a Loraserver issue tracker. Please ask on a Loraserver forum, thanks.
