### ISSUE TITLE
GPS not working in release 1.8.02 

### ISSUE THREAD

**Issue by Habies** [cyberman54/ESP32-Paxcounter#431]
On my Tbeam v10 the serial output gave me a ax192 fail, v1.801 works great.
Also the battery level is incorrect.

**Comment by cyberman54** [comment]
This was a bug in PMU init routine (AXP192), is already fixed. Please use current code.

**Comment by cyberman54** [comment]
@Habies Note, i updated ttgobeam10.h since i got a schematic and test unit today.

See https://github.com/cyberman54/ESP32-Paxcounter/pull/434
