### ISSUE TITLE
Updates in embedded libraries

### ISSUE THREAD

**Issue by spmrider** [cyberman54/ESP32-Paxcounter#452]
I just stumbled on an issue compiling the newest version of the code. It turned out, that I had to manually remove the .pio directory to trigger cloning of a newer version of the MCCI LMIC library. I suspect this is due to the git URL reference instead of a version, but was not able to check by now. a simple _clean_ did not help.
Editor Atom, Platform Linux.

**Comment by cyberman54** [comment]
I pinned version of MCCI LMIC.

https://github.com/cyberman54/ESP32-Paxcounter/pull/453

**Comment by cyberman54** [comment]
Solved.

https://github.com/cyberman54/ESP32-Paxcounter/pull/455
