### ISSUE TITLE
time sync: randomize initial seq. number

### ISSUE THREAD

**Issue by FlorianLudwig** [cyberman54/ESP32-Paxcounter#463]
As described in https://github.com/cyberman54/ESP32-Paxcounter/pull/459#issuecomment-538424494 the initial seqNumber should be randomized:

timesync.cpp#L28: static uint8_t time_sync_seqNo = 0; - maybe we should initialize with a random number, to ensure that new starting devices do not get outdated data for seqNo "0" from Lora networkserver buffer (e.g. when devices re-join) -- @cyberman54

**Comment by cyberman54** [comment]
[Ready](https://github.com/cyberman54/ESP32-Paxcounter/commit/01fb7c53b4e44719bfd95a896ddcb5c62f347451). 
Can you please test?
