### ISSUE TITLE
Timezone handling is broken

### ISSUE THREAD

**Issue by cyberman54** [cyberman54/ESP32-Paxcounter#464]
Enhancement of timesync protocol does conflict with timezone handling on the device, resulting in a 2 hours offset. Timezone handling on the device is based on [Timezone Library](https://github.com/JChristensen/Timezone) and is further needed for syncing time by GPS.

**Comment by mariusgripp** [comment]
https://github.com/cyberman54/ESP32-Paxcounter/pull/466
