### ISSUE TITLE
Support function turn off over push-button for TTGO T-Beam, new version

### ISSUE THREAD

**Issue by theArcher73** [cyberman54/ESP32-Paxcounter#468]
The TTGO-Beam in the new version has no power slide switch but only button. In the standard version (script of the delivery) a function is implemented which can be used to switch off the beam. If it is possible to integrate this function into the Sketch of the Paxcounter, always wait until the battery is empty, .... - not so nice. 

Thanks a lot!
Archer

**Comment by cyberman54** [comment]
This "on/off button longpress" feature is already implemented in current code in development branch, and will be part of master with next release. Please use (and test) code in development branch with your T-Beam V10. Long press of left most button = power off (sleep mode) / short press of middle button = wake up (after sleep).

**Comment by cyberman54** [comment]
@theArcher73 oh wait, even better: The function is already part of master code, since v1.8.34.
So just rebuild from current master, reflash, and you have it.
