### ISSUE TITLE
ttgo v1 board cant join ttn

### ISSUE THREAD

**Issue by raystream** [cyberman54/ESP32-Paxcounter#471]
Hello,
i have a ttgo v1 board here and flashed the pax counter 1.9.6 on it.
I changed the config files as described but i only get a JOIN_WAIT.
And i can not see any Data in ttn.
the blue led above the charge led is fast flashing

here is the log output:

`I (21237) wifi: ic_enable_sniffer
[I][main.cpp:379] setup(): Starting Interrupt Handler...
[I][main.cpp:401] setup(): Starting Timers...

[I][main.cpp:459] setup(): Starting Timekeeper...
[I][timekeeper.cpp:150] timepulse_init(): Timepulse: internal (ESP32 hardware timer)
[I][main.cpp:466] setup(): Features: OLED LED OTA BLE LORA FILTER PACKED WIFI BTN_PD
1131717: engineUpdate, opmode=0x4
1131827: TXMODE, freq=868500000, len=23, SF=7, BW=125, CR=4/5, IH=0
start single rx: now-rxtime: 2
1448301: RXMODE_SINGLE, freq=868500000, SF=7, BW=125, CR=4/5, IH=0
rxtimeout: entry: 1448629 rxtime: 1448288 entry-rxtime: 341 now-entry: 59 rxtime-txend: 312596
start single rx: now-rxtime: 16
1511104: RXMODE_SINGLE, freq=869525000, SF=9, BW=125, CR=4/5, IH=0
rxtimeout: entry: 1512392 rxtime: 1511076 entry-rxtime: 1316 now-entry: 47 rxtime-txend: 375384
1512688: engineUpdate, opmode=0x4
[I][senddata.cpp:76] sendData(): Counter cleared
4413926: engineUpdate, opmode=0xc
[I][lorawan.cpp:266] lora_send(): 2 byte(s) sent to LORA
5192329: engineUpdate, opmode=0xc
5192415: TXMODE, freq=868100000, len=23, SF=7, BW=125, CR=4/5, IH=0
start single rx: now-rxtime: 1
5508888: RXMODE_SINGLE, freq=868100000, SF=7, BW=125, CR=4/5, IH=0
rxtimeout: entry: 5509217 rxtime: 5508876 entry-rxtime: 341 now-entry: 43 rxtime-txend: 312596
start single rx: now-rxtime: 20
5571694: RXMODE_SINGLE, freq=869525000, SF=9, BW=125, CR=4/5, IH=0
rxtimeout: entry: 5572984 rxtime: 5571664 entry-rxtime: 1320 now-entry: 89 rxtime-txend: 375384
5573315: engineUpdate, opmode=0xc
[I][senddata.cpp:76] sendData(): Counter cleared
9599091: engineUpdate, opmode=0xc
9599179: TXMODE, freq=868300000, len=23, SF=7, BW=125, CR=4/5, IH=0
start single rx: now-rxtime: 2
9915653: RXMODE_SINGLE, freq=868300000, SF=7, BW=125, CR=4/5, IH=0
rxtimeout: entry: 9915980 rxtime: 9915639 entry-rxtime: 341 now-entry: 39 rxtime-txend: 312596
start single rx: now-rxtime: 2
9978440: RXMODE_SINGLE, freq=869525000, SF=9, BW=125, CR=4/5, IH=0
rxtimeout: entry: 9979728 rxtime: 9978427 entry-rxtime: 1301 now-entry: 84 rxtime-txend: 375384
9980080: engineUpdate, opmode=0xc`

**Comment by cyberman54** [comment]
Yes, we have a general join problem.
Unfortunately i could not manage to find the root cause yet.
Any help and analysis is welcome.

**Comment by cyberman54** [comment]
Trying to get some help [here](https://www.thethingsnetwork.org/forum/t/need-help-with-mcci-lmic-and-ttn-join-wait-issue/30846).

**Comment by cyberman54** [comment]
Fixed. Please reload current version and try again.
