### ISSUE TITLE
Program size is greater than maximum allowed. 

### ISSUE THREAD

**Issue by ajpaezm** [cyberman54/ESP32-Paxcounter#479]
I'm getting this message for different reasons:

![image](https://user-images.githubusercontent.com/47114614/67783918-578a2400-fa41-11e9-8c76-4a934dfababa.png)

Some of the scenarios for which this happens are the following:

1) Having the WIFI and BLE sniff flags simultaneously on. 
2) Sometimes by making slight changes to the code (I added a couple of functions for some minor enhancements, like allowing to change the SALT remotely). 

And others, there aren't so many, but they are usually similar to the two described above. I'm constantly going back to the previous version of the code that worked for me but sooner or later I stumble with that again. 

Any hints of how to bypass this issue?

Thanks in advance!

**Comment by cyberman54** [comment]
You're using version 1.7.8., this is obsolete. 
Solution is to upgrade code to current version (1.9.71), then this issue should disappear.

The code is not too big, but in a previous version the build script did not select (bigger) partition table `min_spiffs.csv`.

If it works after code update, please close this issue, otherwise report again here.

**Comment by ajpaezm** [comment]
It worked! Thanks! :)

**Comment by vanminh1310** [comment]
![image](https://user-images.githubusercontent.com/53778428/127806581-bc97dc4b-de38-492a-b1d4-d9986ded0653.png)
Hello i am a newbie. Currently I'm getting this error with my program trying to combine the Wifi and BLE libraries on the ESP32. Can anybody show me how to solve it. Thank you very much

**Comment by vanminh1310** [comment]
![image](https://user-images.githubusercontent.com/53778428/127807258-6ee30f8c-7eca-416c-8e52-738e5c278959.png)
Hello i am a newbie. Currently I'm getting this error with my program trying to combine the Wifi and BLE libraries on the ESP32. Can anybody show me how to solve it. Thank you very much

**Comment by cyberman54** [comment]
@vanminh1310 please post your platformio.ini

**Comment by vanminh1310** [comment]
@cyberman54  
![image](https://user-images.githubusercontent.com/53778428/127811346-1cf12e8e-8acc-4bdc-b9b3-8816e3ec0757.png)

**Comment by cyberman54** [comment]
this is from some other project, not paxcounter.

**Comment by vanminh1310** [comment]
@cyberman54 
I don't quite understand what you mean.

**Comment by cyberman54** [comment]
You have a completely wrong platformio.ini file

**Comment by vanminh1310** [comment]
@cyberman54 
Can you help me. I really can't fix it
