### ISSUE TITLE
"Guru Meditation Error" when WIFICOUNTER is 0.

### ISSUE THREAD

**Issue by ajpaezm** [cyberman54/ESP32-Paxcounter#481]
I would like to scan only BLE, so in the paxcounter.conf I should only set:

```
#define BLECOUNTER                      1       // set it to 1 if you want to use BLE count, at expense of power & memory
#define WIFICOUNTER                     0       // set it to 0 if you want to switch off WIFI count

```
But the following error comes, and then the device (a LoRa32 v2.1) comes up with this error: 

> Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

I can scan BLE when both are on and cfg.blescan = 1. Is there a way to be able to only count BLE using these settings?

Thanks in advance for any help.

**Comment by cyberman54** [comment]
[fixed](https://github.com/cyberman54/ESP32-Paxcounter/commit/f6654a47e7320338601898cea4692931c42f7773)
