### ISSUE TITLE
Log file storage in Memory

### ISSUE THREAD

**Issue by Nethranv** [cyberman54/ESP32-Paxcounter#494]
Hi,

I am trying to implement a C++ code to store the logged data into file since we are not using display. but the file handling doesn't seem to work on Lopy, do you suggest that i need to code in Python ?

**Comment by cyberman54** [comment]
Paxcounter does not use a python environment and will not do so, to keep the footprint of firmware small. There a many ways and libraries to create a data logger in c++, shouldn't bee too complicated. Keep on trying :-)

**Comment by cyberman54** [comment]
see #500

**Comment by Nethranv** [comment]
This is of a great help☺ thanks a ton.
