### ISSUE TITLE
Not compiling - duplicate functions in power/battery.cpp

### ISSUE THREAD

**Issue by mxbranson** [cyberman54/ESP32-Paxcounter#495]
Hi,
Love the project.

Would't compile for a TTGo PAX T3-1.6 via usb.
Kept reporting duplicate functions in battery.cpp and power.cpp
void calibrate_voltage(void)
uint16_t read_voltage()
bool batt_sufficient()
I commented out the battery.cpp versions (as not enabled) and everything worked.

Thanks!

**Comment by cyberman54** [comment]
Please clean your local cache / repository and reload the current code. There is no more battery.cpp file, it was withdrawn a few releases ago.  Possibly you're still holding it locally?
