### ISSUE TITLE
GPS Data

### ISSUE THREAD

**Issue by digitalyours** [cyberman54/ESP32-Paxcounter#498]
I'm struggling with getting GPS data transmitted from my TTGO T-Beam (Start-up sequence [1]). I'm only seeing data over port 01, nothing else can be seen in the TTN monitor. Also I don't see any data transmitted to TTN Mapper integration. This is maybe not a bug, since I'm new to the whole topic. Am I overlooking something?

Best & thx
Christoph

[1]
[D][esp32-hal-psram.c:47] psramInit(): PSRAM enabled
[I][reset.cpp:64] do_after_reset(): Starting Software v1.9.81, runmode 0
[I][main.cpp:148] setup(): This is ESP32 chip with 2 CPU cores, WiFi/BT/BLE, silicon revision 1, 4MB external Flash
[I][main.cpp:150] setup(): Internal Total heap 255108, internal Free Heap 229344
[I][main.cpp:153] setup(): SPIRam Total heap 4194252, SPIRam Free Heap 4194252
[I][main.cpp:156] setup(): ChipRevision 1, Cpu Freq 240, SDK Version v3.2.3-14-gd3e562907
[I][main.cpp:158] setup(): Flash Size 4194304, Flash Speed 40000000
[I][main.cpp:160] setup(): Wifi/BT software coexist version 1.1.7
[I][main.cpp:164] setup(): IBM LMIC version 1.6.1468577746
[I][main.cpp:169] setup(): Arduino LMIC version 3.0.99.5
[I][macsniff.cpp:36] printKey(): DevEUI: xxxxxxx
[I][macsniff.cpp:36] printKey(): AppEUI: xxxxxx
[I][macsniff.cpp:36] printKey(): AppKey: xxxxxx
[I][main.cpp:174] setup(): TinyGPS+ version 1.0.2
[I][configmanager.cpp:190] loadConfig(): Reading settings from NVS
[I][configmanager.cpp:55] open_storage(): Opening NVS
[I][configmanager.cpp:60] open_storage(): Done
[I][configmanager.cpp:204] loadConfig(): NVRAM settings version = 1.9.81
[I][configmanager.cpp:222] loadConfig(): bsecstate = 0
[I][configmanager.cpp:227] loadConfig(): loradr = 5
[I][configmanager.cpp:235] loadConfig(): txpower = 14
[I][configmanager.cpp:243] loadConfig(): adrmode = 1
[I][configmanager.cpp:251] loadConfig(): screensaver = 0
[I][configmanager.cpp:259] loadConfig(): screenon = 1
[I][configmanager.cpp:267] loadConfig(): countermode = 0
[I][configmanager.cpp:275] loadConfig(): sendcycle = 30
[I][configmanager.cpp:283] loadConfig(): wifichancycle = 50
[I][configmanager.cpp:291] loadConfig(): wifiantenna = 0
[I][configmanager.cpp:299] loadConfig(): vendorfilter = 1
[I][configmanager.cpp:307] loadConfig(): rgbluminosity = 30
[I][configmanager.cpp:315] loadConfig(): blescantime = 8
[I][configmanager.cpp:323] loadConfig(): BLEscanmode = 0
[I][configmanager.cpp:331] loadConfig(): WIFIscanmode = 1
[I][configmanager.cpp:339] loadConfig(): rssilimit = 0
[I][configmanager.cpp:347] loadConfig(): payloadmask = 126
[I][configmanager.cpp:355] loadConfig(): Monitor mode = 0
[I][configmanager.cpp:362] loadConfig(): Done
[I][i2c.cpp:33] i2c_scan(): Starting I2C bus scan...
[I][i2c.cpp:81] i2c_scan(): I2C scan done, 0 devices found.
[I][main.cpp:209] setup(): PSRAM found and initialized
[I][main.cpp:243] setup(): Starting LED Controller...
[I][power.cpp:220] calibrate_voltage(): ADC characterization based on reference voltage stored in eFuse
[I][gpsread.cpp:37] gps_init(): Using serial GPS
[I][main.cpp:295] setup(): Starting GPS Feed...
[I][lorawan.cpp:303] lora_stack_init(): LORA send queue created, size 600 Bytes
[I][lorawan.cpp:306] lora_stack_init(): Starting LMIC...
[I][main.cpp:365] setup(): Starting Wifi...
[D][lorawan.cpp:501] myEventCallback(): JOINING         

[D][cyclic.cpp:36] doHousekeeping(): IRQhandler 1960 bytes left | Taskstate = 0
[D][cyclic.cpp:39] doHousekeeping(): LMiCtask 2580 bytes left | Taskstate = 2
[D][cyclic.cpp:42] doHousekeeping(): Lorasendtask 2616 bytes left | Taskstate = 2
[D][cyclic.cpp:46] doHousekeeping(): Gpsloop 1588 bytes left | Taskstate = 1
[D][cyclic.cpp:61] doHousekeeping(): LEDloop 552 bytes left | Taskstate = 2
[I][cyclic.cpp:70] doHousekeeping(): Battery: 4118mV

**Comment by cyberman54** [comment]
Did you study the hints in readme.md how to configure the settings to generate combined messages (pax and gps) on port 1, suitable for ttnmapper?

**Comment by cyberman54** [comment]
"GPS data can also be combined with payload on port 1, #define GPSPORT 1 in paxcounter.conf to enable"

**Comment by digitalyours** [comment]
Yes, I did and just double checked. No GPS data gets transmitted on port 1, just PAX and WIFI...

**Comment by cyberman54** [comment]
@digitalyours sure that you GPS has a fix? If not, intentionally no data is transmitted.
Indicator of "has a fix" is that red PPS LED on T-BEAM is flashing.
Please confirm, thanks.

**Comment by digitalyours** [comment]
Ok, thanks for pointing this out. Indeed there is no red PPS LED flashing. Doesn't matter where I place the board, maybe the GPS is broken. :(

**Comment by cyberman54** [comment]
Paxcounter software does not (yet) configure the GPS chip. Thus the chip will run in default configuration as delivered by your hardware source. If this configuration is faulty, this may cause fix issues.

**Comment by nerdyscout** [comment]
actually this is the reason why #489 is still on draft. Although my device got the fixled blinking, I can the in the terminal `sendData(): No valid GPS position`

**Comment by cyberman54** [comment]
solved by @nerdyscout PR, thanks!

**Comment by digitalyours** [comment]
Many thx for the pr. It worked for me!
