### ISSUE TITLE
Blurry Display on HeltecV2

### ISSUE THREAD

**Issue by tomschlde** [cyberman54/ESP32-Paxcounter#508]
After Updating to the current version the display becomes blurry on heltec V2 - in the former versions the content was excellent. Seems to try grayscale - see screenshot.
![IMG_20191223_194509](https://user-images.githubusercontent.com/59179041/71374942-e6886800-25bc-11ea-938c-3760ae789bb2.jpg)

**Comment by cyberman54** [comment]
Could you please try to increase display contrast value in paxcounter
conf and retry?

**Comment by tomschlde** [comment]
Got it... burn in - the text in the current version is not at the same coodinates.
Can be seen on the other screens.
Have to buy a new one :)

![IMG_20191223_215717](https://user-images.githubusercontent.com/59179041/71380421-63bcd880-25cf-11ea-9456-d4204cedff5f.jpg)

**Comment by cyberman54** [comment]
That's right, the mask was changed, and OLEDs wear out pretty fast. That's why in the new version the contrast was decreased.
