### ISSUE TITLE
Provide pressure-data from BME280 to display

### ISSUE THREAD

**Issue by tomschlde** [cyberman54/ESP32-Paxcounter#519]
![Pressure](https://user-images.githubusercontent.com/59179041/71665149-fe4db200-2d5b-11ea-9797-99451c667787.jpg)

works fine...

display.cpp

#if (HAS_BME)
// line 2-3: Temp
dp_printf(0, 2, FONT_STRETCHED, 0, "TMP:%-2.1f", bme_status.temperature);

// line 4-5: Hum
dp_printf(0, 4, FONT_STRETCHED, 0, "HUM:%-2.1f", bme_status.humidity);

add    // line 6-7: Pre
add    dp_printf(0, 6, FONT_STRETCHED, 0, "PRE:%-2.1f", bme_status.pressure);

sorry about the bad formatting here - iserting 'code' does not really work.

**Comment by cyberman54** [comment]
added.
Thanks!
