### ISSUE TITLE
Refactor gps decoding using sparkfun lib

### ISSUE THREAD

**Issue by cyberman54** [cyberman54/ESP32-Paxcounter#521]
https://github.com/sparkfun/SparkFun_Ublox_Arduino_Library/blob/master/src/SparkFun_Ublox_Arduino_Library.h

Advantages:
- lib can use either serial or i2c connect of gps module
- lib can use UBX mode of ublox modules, reducing NMEA parsing traffic

Disadvantages:
- does work only with ublox chips, so LoPy Expansion module cannot be supported (has Quectel GPS)

**Comment by hansju-11** [comment]
Maybe we can use preprocessor to define something like GPS_LIB_TIP  1 or 2.
1 or not set means use TinyGSP and 2 means use Ublox. 
This will fix #671 too.

Second, can somebody test, if the ublox can parse NMEA over serial an i2c from other devices? I do not have an Quectel right now.

**Comment by cyberman54** [comment]
What about any license restrictions on ublox lib? Paxcounter is open source.

**Comment by hansju-11** [comment]
It is MIT License. 

From my point of view it should be ok, as long if we include a remark on that license.

 


 

https://github.com/sparkfun/SparkFun_u-Blox_NEO_M9N/blob/master/LICENSE.md

 

 

 

Gesendet: Sonntag, 11. April 2021 um 21:01 Uhr
Von: "Verkehrsrot" ***@***.***>
An: "cyberman54/ESP32-Paxcounter" ***@***.***>
Cc: "hansju-11" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [cyberman54/ESP32-Paxcounter] Refactor gps decoding using sparkfun lib (#521)


 

What about any license restrictions on ublox lib? Paxcounter is open source.

**Comment by cyberman54** [comment]
I think it could with generic NMEA GNSS outputs, too. Look in this example:
https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/blob/master/examples/Example2_NMEAParsing/Example2_NMEAParsing.ino

**Comment by hansju-11** [comment]
Short Update, 
I did some test with the LIB, but I did not get it to work. 
It looks like per default the NEO6 is sendig only NMEA infos. If I set the output to UBLOX only I did not get any infos. I can still send commands in ublox. It looks like there is an output filter active. Than I set up a path through from GPS to usb/Serial and use the u-center software. Here I can change the config and setup the right outputfilter and I got ublox infos. 
But when I switch bach to the lib I got only wrong data.
I'm still in hope :-) maybut somebody has some other information and can share this here. I will try to see if we get this to run.

**Comment by cyberman54** [comment]
@hansju-11 another option could be the [NeoGPS](https://github.com/SlashDevin/NeoGPS) library.

**Comment by cyberman54** [comment]
Solved in v3.2.0 without sparkfun lib, but by own code :-)

**Comment by hansju-11** [comment]
> Solved in v3.2.0 without sparkfun lib, but by own code :-)

Cool
