### ISSUE TITLE
Screencycling

### ISSUE THREAD

**Issue by rdmueller** [cyberman54/ESP32-Paxcounter#523]
for devices without a button, it would be nice if the screen/display cycles every x seconds.
In addition, it would be great if this mode skips screens without information (no GPS, no BME).

**Comment by cyberman54** [comment]
Good idea, let's see if anyone implements it.

**Comment by rdmueller** [comment]
I am new to the paxcounter, but I guess I am already halfway through the implementation...

**Comment by cyberman54** [comment]
Page skip is ready (experimental), look [here](https://github.com/cyberman54/ESP32-Paxcounter/commit/e8abe8567bca1d618a4357c2e4163f8db40535b5)

Page cycling yet to come.

**Comment by cyberman54** [comment]
@rdmueller Done:
https://github.com/cyberman54/ESP32-Paxcounter/commit/f960627910be691656addaf713e03b5237a20aee
Could you please test and report here? Thanks.

**Comment by cyberman54** [comment]
Done.

**Comment by rdmueller** [comment]
sorry, it took a while but today I found some time to give it a try. Works like a charm!
