### ISSUE TITLE
TTGO V1 SX127x pin

### ISSUE THREAD

**Issue by DierkJ** [cyberman54/ESP32-Paxcounter#577]
Hi Cyberman,

first of all: Thanks for the great project!
I found a little issue with the TTGO V1 hardware, which results in a non working LMIC.  The DIO2 pin is wired to pin 32 of the ESP on my TTGO V1 board.  Leaving the pin LMIC_UNUSED_PIN will not wakeup the SX1272.

Exchange
  `#define LORA_IO2  LMIC_UNUSED_PIN`
to
  `#define LORA_IO2  (32) ` 
will solve this.

**Comment by cyberman54** [comment]
DIO2 pin ist not used for LORA modulation, only for FSK (timeout signal).
Thus, if you do not use FSK, DIO2 ist not needed.

**Comment by DierkJ** [comment]
Sorry for my typo about the SX1272.  My TTGO V1 is using the SX1276. Just double-checked on the pcb.

If the Dio2 is set to unused the first call to txlora() will fail in line 799:
`   opmodeLora();`
`    ASSERT((readReg(RegOpMode) & OPMODE_LORA) != 0);`

Looks like the SX is not switched to Lora.

**Comment by mabuberg** [comment]
I have a TTGO V1 using a SX1276 too. It doesn't connect to TTN. It outputs "JOINING" on the display and shortly after "TXSTART" where it stays.
I tried switching LORA_IO2 to (32). Same behavior.

Thank you for your work!

**Comment by cyberman54** [comment]
Thank you guys for Investigating this. Could you please
1) open Pull Request for the hal files of boards which have DIO2 wired

2) Open pull request for boards which do not have DIO2 wired (add note that is has to be manually wired)

3) raise an issue in MCCI LMIC repository

?

Thanks.

**Comment by DierkJ** [comment]
My TTGO V1 looks like this:
![ttogv1](https://user-images.githubusercontent.com/58705960/77464745-ebe98e80-6e07-11ea-9c06-4f48a75d108a.jpg)

**Comment by cyberman54** [comment]
This is not the "original" TTGO T1, looks like a fake Heltec board.

**Comment by cyberman54** [comment]
PR merged.
