### ISSUE TITLE
FAILURE on Starting LMIC... [TTGOv1]

### ISSUE THREAD

**Issue by neolinux** [cyberman54/ESP32-Paxcounter#580]
Hello,

anyone got it to work on ttgov1? 

Oled doesent work (is enabled in the configuration)

and in the console i become this error:

`
[I][lorawan.cpp:297] lora_stack_init(): LORA send queue created, size 600 Bytes
[I][lorawan.cpp:300] lora_stack_init(): Starting LMIC...
FAILURE 
.pio\libdeps\usb\MCCI LoRaWAN LMIC library_ID5774\src\lmic\radio.c:799
`

any help?

Thank You.

**Comment by neolinux** [comment]
I have this board

![image](https://user-images.githubusercontent.com/1484386/77832012-22d6e180-7133-11ea-9b37-34b6df4781d2.png)

**Comment by cyberman54** [comment]
@DierkJ can you help here? Same board as yours?

**Comment by cyberman54** [comment]
@neolinux please try version from development branch and make these patches:

add to / change in `TTGOV1.h`:

> #define MY_OLED_ADDR 0x3D
> #define LORA_IO2  LMIC_UNUSED_PIN

**Comment by neolinux** [comment]
Same thing, oled is black (it worked as i became the ttgov1 with the demo firmware) and nothing in TTN/same error in the terminal of VS Code.

**Comment by neolinux** [comment]
I've got the lorawan to work:

i changed this:

// enable only if you want to store a local paxcount table on the device
#define HAS_SDCARD  1      // this board has an SD-card-reader/writer
// Pins for SD-card
#define SDCARD_CS    (37)
#define SDCARD_MOSI  (38)
#define SDCARD_MISO  (36)
#define SDCARD_SCLK  (39)

**Comment by neolinux** [comment]
For the OLED, what i see in the example sketch of ttgov1:

digitalWrite (16, LOW); // set GPIO16 low to reset OLED
  delay (50);
  digitalWrite (16, HIGH); // while OLED is running, GPIO16 must go high

it is implemented in the ESP32-Paxcounter code?

**Comment by cyberman54** [comment]
Why did you enable the SD card function? Your picture is showing a board without SD card slot?

**Comment by neolinux** [comment]
It doesn’t compile with define HAS_SDCARD 0

**Comment by cyberman54** [comment]
you need to comment the define:
// define HAS_SDCARD 1

**Comment by cyberman54** [comment]
try to set on ttgov1.h

#DEFINE MY_DISPLAY_RST 16

**Comment by neolinux** [comment]
Ok, i've commented the HAS_SDCARD definition, no compilation error :-P

With the #DEFINE MY_DISPLAY_RST 16 the oled continues to be black, so it doesent work.

**Comment by cyberman54** [comment]
please reload code from development branch (v1.9.982), the use ttgov1.h without any modifications. Should work then.

**Comment by neolinux** [comment]
It works now!

Thank You ;)
