### ISSUE TITLE
'oledShutdown' was not declared in this scope

### ISSUE THREAD

**Issue by neolinux** [cyberman54/ESP32-Paxcounter#582]
Master branch:

src\display.cpp: In function 'void dp_shutdown()':
src\display.cpp:486:25: error: 'oledShutdown' was not declared in this scope
     oledShutdown(&ssoled);
                         ^
Compiling .pio\build\usb\src\ledmatrixdisplay.cpp.o
*** [.pio\build\usb\src\display.cpp.o] Error 1

**Comment by nottheedge** [comment]
Insert „void oledShutdown(SSOLED *pOLED);“ in ss_oled.h resolved it for me

**Comment by cyberman54** [comment]
This is already fixed with current 4.1.2, use `oledPower()` instead.
