### ISSUE TITLE
how to enable BATT_DATA in uplink?

### ISSUE THREAD

**Issue by robomotic** [cyberman54/ESP32-Paxcounter#589]
Hello there again!

**Board:**
LILYGO® TTGO LORA V1.3 868Mhz ESP32 Chip SX1276 Module 0.96 Inch OLED Screen WIFI And Bluetooth Development Board

**Setup:**

OS: Darwin x64 18.7.0
VSS Code: Version: 1.43.2
Platform IO: Core 4.3.1 Home 3.1.1
TTN Server: Enterprise
Gateway: Kona Mikro Gateway

**Steps:**

Clone Git Project from PlatformIO
Change platform.ini to: halfile = ttgov21new.h
Copy loraconf sample and ota.conf
In loraconf enable LORA_ABP
Paxcounter: 

**Issue:**
I don't see any PORT 8 battery packets in the uplink

**Observations**
In the serial debug output I do see the correct battery readings.

In configmanager.c I see this line:

> #define PAYLOADMASK                                  \
>   ((GPS_DATA | ALARM_DATA | MEMS_DATA | COUNT_DATA | \
>     SENSOR1_DATA | SENSOR2_DATA | SENSOR3_DATA) &    \
>    (~BATT_DATA) )

Should I remove the nor to look like this?

> #define PAYLOADMASK                                  \
>   ((GPS_DATA | ALARM_DATA | MEMS_DATA | COUNT_DATA | \
>     SENSOR1_DATA | SENSOR2_DATA | SENSOR3_DATA) &    \
>    (BATT_DATA) )

How often is going to be sent?

**Comment by cyberman54** [comment]
See readme.md, use rcommand 0x16 to set battery data on/off
