### ISSUE TITLE
Downlink remote control TTN explanation

### ISSUE THREAD

**Issue by robomotic** [cyberman54/ESP32-Paxcounter#590]
Hello!
I have a very simple operation to perform: 

I want to send a Remote Control operation on Port 2 to get the device status which is 0x81 and another command which is 0x16 to enable the battery level reading.

Would it be something along the lines of:

> 0x81 0x01
> 0x16 0x01

Then encode in BASE64?

How do I generate the payload bytes for the TTN console?

Cheers.

**Comment by cyberman54** [comment]
you can just enter the command payload in plain text (hex) in the TTN console in downlink field. You can combine both commands in one downlink packet: 81 01 16 01

**Comment by ScholliYT** [comment]
Maybe add this to the Readme file? Wasn't clear to me at first.

**Comment by cyberman54** [comment]
@ScholliYT You're welcome to post a PR for readme.md
