### ISSUE TITLE
Controlling the Screens that Appear in the Display Cycle

### ISSUE THREAD

**Issue by jamessugrue** [cyberman54/ESP32-Paxcounter#602]
Hi 
I'm just wondering how I can control the screens that appear when OLED is enabled so that it only displays one rather than cycling through three. Is there a way of doing that?  

Thanks

**Comment by cyberman54** [comment]
Display cycling is active, if a device has no button or no button is defined. If a device has a button, display pages are flipped on button press.

So, easiest way to suppress display cycling is to define a button in <$MYHALFILE.>, even if there is no one. Then only the first screen will be shown.

**Comment by jamessugrue** [comment]
Thank you so much!
