### ISSUE TITLE
Net time acquire

### ISSUE THREAD

**Issue by simoneflori81** [cyberman54/ESP32-Paxcounter#611]
I've never been able to acquire net time from the network, is there something I should customize for that?
Thanks

**Comment by cyberman54** [comment]
You must enable it in paxcounter.conf, and you must ensure that your network provider support DevTimeReq.

Please, close this issue, as long as you did not discover an issue with this software.

**Comment by simoneflori81** [comment]
Thanks for the hint, I'll try that.
