### ISSUE TITLE
ESP32-Paxcounter V1.9.996 / VSC: Der Bezeichner ""DAYLIGHT_TIME"" ist nicht definiert.

### ISSUE THREAD

**Issue by GeorgWolter** [cyberman54/ESP32-Paxcounter#613]
V1.9.996 / TTGO Beam T22_V1.0, 20190612
Visual Studio Code / Version: 1.46.0

Folks,,
I am just running into this issue. And date / time are not getting updated on the display:

Der Bezeichner ""PAYLOAD_BUFFER_SIZE"" ist nicht definiert.
Der Bezeichner ""DAYLIGHT_TIME"" ist nicht definiert.
Der Bezeichner ""STANDARD_TIME"" ist nicht definiert.
Der Bezeichner ""HAS_LED"" ist nicht definiert.
Der Bezeichner ""SENDCYCLE"" ist nicht definiert.
Der Bezeichner ""HOMECYCLE"" ist nicht definiert.

Hopefully any Prrro here finds some time for sharing a hint :-)
Thank you!
![Issue_1662020](https://user-images.githubusercontent.com/61526104/84793109-04c3a380-aff5-11ea-8fbb-d03dc7063bd4.jpeg)

**Comment by cyberman54** [comment]
Did you install platform.io?

**Comment by GeorgWolter** [comment]
Yes, platform.io (C4.3.4 / H3.2.3) works fine and VSC build / upload runs successfully too.
I am using same  platform.io and VSC for other projects as well. No trouble.
Interesting: There is no such error with the ESP32-Pax release from March.

**Comment by cyberman54** [comment]
I can't reproduce this with platformio core 4.3.4.

**Comment by GeorgWolter** [comment]
That's good news. Thx.
Do you have any idea I how could somehow solve the problem maybe?

**Comment by AugustQu** [comment]
can't reproduce this.
platformio core: 4.3.4
Visual Studio Code 1.46.0

DAYLIGHT_TIME is used in main and defined in paxcounter.conf.

**Comment by cyberman54** [comment]
Code was migrated to Platformio 5.0, this issue cannot be reproduced. Closing.
