### ISSUE TITLE
Bluetooth zählt nicht

### ISSUE THREAD

**Issue by ChrSchultz** [cyberman54/ESP32-Paxcounter#618]
mein TTGO Lora32 zeigt immer an BLTH:0 obwohl mein Handy bluetooth eingeschaltet ist. 
Log:

    [V][blecsan.cpp:115] gap_callback_handler(): BT payload rcvd -> type: 0x03 -> Complete List of 16-bit Service Class UUIDs
    [V][blecsan.cpp:136] gap_callback_handler(): Device address (bda): 7b:58:26:80:53:50
    [V][blecsan.cpp:138] gap_callback_handler(): Addr_type           : BLE_ADDR_TYPE_RANDOM
    [V][blecsan.cpp:139] gap_callback_handler(): RSSI                : -90
    [V][blecsan.cpp:152] gap_callback_handler(): BT device filtered

**Comment by spmrider** [comment]
Einmal den MAC Address-Filter ausschalten bitte. Welcher Handyhersteller ist das?

**Comment by cyberman54** [comment]
is local OUI bit set? Then it's a random local OUI.

**Comment by ChrSchultz** [comment]
SAMSUNG J6
Ohne MAC-Filter zählt er.

**Comment by cyberman54** [comment]
Thus, it's a vendor filter effect, the OUI will be missing in vendor_array.h
