### ISSUE TITLE
Rework sniffing parser

### ISSUE THREAD

**Issue by cyberman54** [cyberman54/ESP32-Paxcounter#62]
On esp32.com forum i found some posts where packet loss is reported, while capturing packets in promiscuous mode. We should validate that our code doesn't have this problem, or, if there is a packet loss, we should try to calculate the quote. Setup could be a surrounding with defined Wifi traffic in the air, then capturing with paxcounter and parallel on a PC with wireshark, then compare results.

[Post packet loss 1](https://www.esp32.com/viewtopic.php?f=13&t=4145)
[Post packet loss 2](https://www.esp32.com/viewtopic.php?f=13&t=2517&p=11845&hilit=promiscuous#p11845)

**Comment by cyberman54** [comment]
Rework packet parser `wifi_sniffer_packet_handler()` in wifiscan.cpp using logics from this [template](wifi_sniffer_packet_handler) to increase counting precision

**Comment by Nethranv** [comment]
Please reshare the template , its not opening.

**Comment by cyberman54** [comment]
@Nethranv > Please reshare the template , its not opening.

Link updated.

**Comment by cyberman54** [comment]
Done with v2.0.4.
