### ISSUE TITLE
Paxcounter value just get bigger and bigger

### ISSUE THREAD

**Issue by StefanBoehnert** [cyberman54/ESP32-Paxcounter#637]
Hello,

I got a weird issue where the results seem to get bigger and bigger. Maybe the new values get added to the old ones I don't know... 

![grafik](https://user-images.githubusercontent.com/24409477/93860422-61eb8700-fcbf-11ea-9181-3c3c7f700022.png)

Did I do something wrong in the settings? I set the counter mode to 'cyclic', seems like the code is ignoring the counter mode setting.

**Comment by cyberman54** [comment]
This looks like you have set cumulative mode. Note: mode is saved in NVRAM and restored, even if you reflash the board. To set new mode, use remote command (see readme), or manually clear the NVRAM of your board.
