### ISSUE TITLE
Payload after switching of wifi_scan via ttn uplink wrong.

### ISSUE THREAD

**Issue by ChrSchultz** [cyberman54/ESP32-Paxcounter#642]
the standard payload with wifi and ble is 2 Byte wifi and 2 Byte ble. eg.
 `00 1D 00 03 ` for for 11 wifi and 3 ble 
if I switch wifi_scan to off via Uplink on port 2 with `17 00`
the payload will be for ble:  03 00 and will be interpretet by decoder with `pax: 3 , wifi: 3`
it should be `00 00 00 03` for `ble: 3`

![grafik](https://user-images.githubusercontent.com/10460405/94365148-ce56f380-00ce-11eb-9113-b250b2c42b39.png)

**Comment by cyberman54** [comment]
fixed.
Thanks for spotting this bug.

**Comment by cyberman54** [comment]
https://github.com/cyberman54/ESP32-Paxcounter/commit/01f990d17f8429dd4c824fd62e145546c611ed6f
