### ISSUE TITLE
[Info] auf meinem Blog: mit dem Paxcounter Corona-Apps zählen

### ISSUE THREAD

**Issue by AugustQu** [cyberman54/ESP32-Paxcounter#654]
Hi,

ich habe mich mal hingesetzt und geschaut, wieviele Personen die Corona-App installiert haben.

Hier präsentiere ich meine Zahlen: [Suche die Zahl 64879](https://linux-fuer-wi.blogspot.com/2020/10/suche-die-zahl-64879.html)

**Comment by cyberman54** [comment]
Link added to README.
Thanks!
