### ISSUE TITLE
heltec boot looping

### ISSUE THREAD

**Issue by dh47** [cyberman54/ESP32-Paxcounter#656]
Following this guide and programming with the Heltec V1.

I get a screen showing the pax counter but then the screen disappears and goes blank then shows again boot looping?

After monitoring in serial I get this error.

10:00:47.357 > [I][lorawan.cpp:203] get_hard_deveui(): Could not read DEVEUI from serial EEPROM

**Comment by cyberman54** [comment]
This looks like you compiled the software for board "generic.h", instead for "heltec.h".
Check your settings in platformio.ini. If you're new to this project, follow installation steps in readme.md carefully.
You MUST edit some files before compiling the software.

**Comment by dh47** [comment]
Ok, thanks I'll try that.

**Comment by dh47** [comment]
Ok, I have followed the guide again and made sure I had the board selected in that ini file.  I get further this time with the main screen and then what looks to be a QR code, but then nothing after that.

**Comment by dh47** [comment]
Master.

**Comment by dh47** [comment]
Hangs on.
`10:18:25.506 > [I][lorawan.cpp:305] lora_stack_init(): Starting LMIC...`

**Comment by cyberman54** [comment]
looks like a wrong pin mapping. Please specify exact version of heltec board you are using and post a high res picture of the board here.

**Comment by dh47** [comment]
WiFi LoRa 32

![20201007_193702](https://user-images.githubusercontent.com/909007/95296133-bd7b5e80-08d4-11eb-8794-2d578b384f6e.jpg)
![20201007_193654](https://user-images.githubusercontent.com/909007/95296138-bf452200-08d4-11eb-8dad-503c52c51c85.jpg)

**Comment by cyberman54** [comment]
I tested current code in master with a Heltec v1 board which has same shape as the board shown here. No issues, software starts and joins.

Check your board version and matching settings in heltec.h carefully, e.g. radio chip type. Try CFG_SX1272_radio (instead of 1276) in heltec.h

**Comment by cyberman54** [comment]
PS: your board has not the printing "868-915Mhz" on the backside. So it probably will have radio chip SX1272. You need to adjust heltec.h as explained above. Software should work then, but you won't be able to use 868 MHz LORAWAN networks with this version. Depends on you country and LORAWAN provider.

**Comment by dh47** [comment]
Hi, it was sent to me from a friend who says its the 433MHz model, but he's not sure.  I will try and compile with the SX1272.
