### ISSUE TITLE
SD Card Not Found, One is pluged in

### ISSUE THREAD

**Issue by dh47** [cyberman54/ESP32-Paxcounter#657]
The serial monitor is saying the card isn't plugged in when one is.  

Do I need to format it in fat32 or NTFS?

```
03:22:47.795 > [I][sdcard.cpp:17] sdcard_init(): looking for SD-card...
03:22:47.802 > [I][sdcard.cpp:37] sdcard_init(): SD-card not found
```

**Comment by dh47** [comment]
Fixed.

By changing this #define HAS_SDCARD  2.

**Comment by cyberman54** [comment]
What type of board are you using?
I never saw a Heltec V1 with SD card reader.
