### ISSUE TITLE
Compilation error display.cpp

### ISSUE THREAD

**Issue by bbreton09** [cyberman54/ESP32-Paxcounter#668]
Hi, i try to update to master branch but i have a compilation problem.
I use a TTGO-BEAM T22-V07
I use : halfile = ttgobeam.h
I just enable display by uncomment #define HAS_DISPLAY 1 in ttgobeam.h

The last version i can build and it work fine is the 1.9.98.

```
Linking .pio\build\usb\firmware_ttgobeam_v2.0.3.elf
.pio\build\usb\src\display.cpp.o:(.literal._Z11dp_drawPagelb+0xa8): undefined reference to `cwa_report()'
.pio\build\usb\src\display.cpp.o: In function `dp_drawPage(long, bool)':
D:\Users\user.name\Documents\PlatformIO\Projects\ESP32-Paxcounter-master/src/display.cpp:694: undefined reference to `cwa_report()'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\usb\firmware_ttgobeam_v2.0.3.elf] Error 1
```
Thank's for your help.

**Comment by cyberman54** [comment]
fixed.

https://github.com/cyberman54/ESP32-Paxcounter/commit/8a0a3949fdac7c7e7d14bd2dfcc524a3fb100af2
