### ISSUE TITLE
Plz add Code and Option for Solar cell adc mesure and more Soil Moisture sensor

### ISSUE THREAD

**Issue by caasisaac** [cyberman54/ESP32-Paxcounter#672]
Good morning, afternoon, night

I don't know much about how to get the readings and play to be transmitted by the lora

for that reason they can help me ..

hello I saw that has the battery meter ADC already activated this worked and is being transmitted by the lora with resistor 100k / 100k all ok very good 

would it be possible to add another ADC function to measure solar cell? 
does not need to be displayed on the display only transmitted by the lora
In addition to the solar cell add another ADC for capaitive Soil Moisture Sensor

I would be very grateful.

**Comment by cyberman54** [comment]
This is open source software, and you have a working example how to use the ADC. Why not going yourself to improve the code?
