### ISSUE TITLE
Include Arduino IDE support

### ISSUE THREAD

**Issue by almol** [cyberman54/ESP32-Paxcounter#677]
Hi.
Please include procedure to compile & upload via Arduino IDE platform instead of Platform.io.
You reach more wide public for you app.
May be this help:
https://community.platformio.org/t/make-platformio-project-compatible-with-arduino-ide/3368/4
...I try but I can't work for me.
Thanks.

**Comment by cyberman54** [comment]
I am sorry, but i won't do this, because the software is too complex for Arduino IDE platform.
