### ISSUE TITLE
TTGO t-beam t22_v1.1 with SX1262 not working

### ISSUE THREAD

**Issue by BugsonPL** [cyberman54/ESP32-Paxcounter#684]
18:08:18.786 > [I][lorawan.cpp:260] lora_stack_init(): LORA send queue created, size 600 Bytes
18:08:18.786 > [I][lorawan.cpp:263] lora_stack_init(): Starting LMIC...
18:08:18.786 > FAILURE
18:08:18.786 > .pio\libdeps\usb\MCCI LoRaWAN LMIC library\src\lmic\radio.c:1164

I used 
halfile = ttgobeam10.h

**Comment by cyberman54** [comment]
SX1262 is not supported by LMIC, so this can't work.

**Comment by BugsonPL** [comment]
Maybe ?
https://github.com/beegee-tokyo/SX126x-Arduino
