### ISSUE TITLE
Counting passengers with multiple devices

### ISSUE THREAD

**Issue by wkulesza** [cyberman54/ESP32-Paxcounter#722]
Hi, first of all, congrats on this project.
I managed to get the Pax counter running with standard code and it seems to work (but the counted number of people around it, changes all the time, eventhough we’re testing it in the office).

My question is: When there are 2 people entering the office with 5 devices (one has 3 cell phones, one has 1 cellphone and 1 tablet). Is it possible to count them as 2, or only possible to count them as 5 ?

Thanks for help in that or any pointers.

**Comment by cyberman54** [comment]
The concept of wifi / bluetooth sniffing counts all MACs in the air, regardless from what type of device they originate and regardless if it's a randomized local MAC or a universal MAC fixed to one device. So you never will get counts with absolute precision. The concept focuses on differential analysis of data gathered over time or at different locations.
