### ISSUE TITLE
FAILURE in TTGO T-Beam v1.1 LoRa SX1262

### ISSUE THREAD

**Issue by hpsaturn** [cyberman54/ESP32-Paxcounter#742]
Hi everyone, 

I don't if this is a error, or maybe this board right now is unsupported for the project, but I have a [T-Beam v1.1 board](https://www.aliexpress.com/item/4001287221970.html) and I chose the `halfile = ttgobeam10.h` hal option but after upload the firmware it gives:

```bash
10:33:18.309 > [I][lorawan.cpp:244] lmic_init(): LORA send queue created, size 530 Bytes
10:33:18.309 > FAILURE 
10:33:18.309 > .pio/libdeps/usb/MCCI LoRaWAN LMIC library/src/lmic/radio.c:1164
```

My LMIC config is:

```cpp
#define CFG_eu868 1
#if !(defined(CFG_sx1272_radio) || defined(CFG_sx1276_radio))
#define CFG_sx1276_radio 1
#endif

#define LMIC_ENABLE_DeviceTimeReq 1

#define LMIC_FAILURE_TO Serial

#define DISABLE_PING

#define USE_IDEETRON_AES
```

The SX1262 radio is incompatible? I ask it because I can see that another user using it: 
https://github.com/cyberman54/ESP32-Paxcounter/issues/671

**Comment by cyberman54** [comment]
Paxcounter is based on [MCCI LMIC LORAWAN stack](https://github.com/mcci-catena/arduino-lmic), which does not support SX1262 chip. Thus, choose the SX1276 variant of T-Beam 1.1, or disable LORA.
