### ISSUE TITLE
TTGO Lora32 V1, Uhrzeit stellen, Display inhalte Ändern

### ISSUE THREAD

**Issue by Lordcybertracker** [cyberman54/ESP32-Paxcounter#746]
Hallo, 
ich habe ein paar mehr Baustelle und fragen

1. ich habe einen TTGO Lora32 V1
https://de.aliexpress.com/item/32840238513.html
Das ist der ganz alte ohne SD Karte.
Aber egal was ich an Hardware auswähle entweder geht das Display nicht, Läßt sich nicht beschreiben oder Lora verbindet nicht.
Was muss ich da einstellen oder könnte man das hinzufügen?

2. Wie bekomme ich die Uhr auf dem gestellt?

3. Wie kann ich das Display änder. Im Laufverkehrsbereich reicht es ja die Zahl ob Joined, TX und Datum  mit Uhrzeit anzeigt.
Danke

**Comment by cyberman54** [comment]
If you need support, please use section Discussion.
Please don't open issue, unless you are not sure to report a software bug.
Thx.
