### ISSUE TITLE
SDS011: new library

### ISSUE THREAD

**Issue by AugustQu** [cyberman54/ESP32-Paxcounter#751]
there is a new library at https://github.com/ricki-z/SDS011

Didn't test it yet but it looks good.

**Comment by cyberman54** [comment]
Unfortunately the author did not create a release (yet?), so there is no trigger in platformio to update the lib.
This is why paxcounter always grabs the latest HEAD from github repo of this lib.
Thus, if you recompile your paxcounter code, you will automatically pull in the latest version of this lib.
