### ISSUE TITLE
WIFI_SSID and WIFI_PASS not declared

### ISSUE THREAD

**Issue by sinalco92** [cyberman54/ESP32-Paxcounter#776]
I become a compiling Error in the "src/boot.cpp" data, because WIFI_SSID and WIFI_PASS are not declared.

`src/boot.cpp: In function 'void start_boot_menu()':`

`src/boot.cpp:88:22: error: 'WIFI_SSID' was not declared in this scope`
`   const char *ssid = WIFI_SSID;`

`src/boot.cpp:89:26: error: 'WIFI_PASS' was not declared in this scope`
`   const char *password = WIFI_PASS;`

**Comment by cyberman54** [comment]
Did you create ota.conf?

**Comment by sinalco92** [comment]
> Did you create ota.conf?

Yes I change the ota.sample.conf to ota.conf
But I dosen’t change anything in the ota.conf

**Comment by cyberman54** [comment]
I can't reproduce this. Maybe an issue with your toolchain?
The defines `WIFI_SSID `and `WIFI_PASS `are created dynamically in buildscript `build.py`.
Please check if this works on your platform.

**Comment by sinalco92** [comment]
> I can't reproduce this. Maybe an issue with your toolchain?
> The defines `WIFI_SSID `and `WIFI_PASS `are created dynamically in buildscript `build.py`.
> Please check if this works on your platform.

Ok now it works.
The `build.py` was not in the project folder. 
Sorry for that, it was my mistake
Thanks for supporting!
