### ISSUE TITLE
define code guidelines

### ISSUE THREAD

**Issue by FlorianLudwig** [cyberman54/ESP32-Paxcounter#78]
The project is missing code guidelines leading to several inconsistencies.

Starting with the simple stuff like spacing, new line characters, etc. I would like to suggest to follow some existing guide and run a reformatting tool like `clang-format` on the project. This will disrupt the development once since all work-in-progress patches might have some simple merge conflicts afterwards but we reach a clean state.

**Comment by cyberman54** [comment]
Done.
