### ISSUE TITLE
Opcode 86 should report if Opcde 88 was used to sync the time (enhancement)

### ISSUE THREAD

**Issue by hansju-11** [cyberman54/ESP32-Paxcounter#786]
It looks like, if I use opcode 86 get time after opcode 88 setTime the status is not reported on the right way.

it reports status to 0x23

**Comment by cyberman54** [comment]
This is indeed another bug, which came in after introducing new timesource __set_ for opcode 86.

**Comment by cyberman54** [comment]
fixed in delevopment branch.
