### ISSUE TITLE
need some clarification about mac_queue_size

### ISSUE THREAD

**Issue by secco04** [cyberman54/ESP32-Paxcounter#798]
Hi everyone, 
we are planning to distribute some paxcounters around the city to measure the people flow.
Now the question is what the mac queue  is for or how does it work if the paxcounter counts 50+ unique mac addresses...

will it count duplicate devices since the queue of the stored mac queue is full or anything other :D

**Comment by cyberman54** [comment]
You don't need think in the MAC queue, it's only for buffering peaks. 50 ist more than enough, even in crowded areas.

Tip: Use the software in development branch. It features a much more efficient method to avoid duplicates. The dev branch is stable, the current version will be released as v2.5.0 in master soon.
