### ISSUE TITLE
Warning! Could not find the package with 'bitbank2/OneBitDisplay @ ^1.10.0' requirements for your system 'windows_amd64'

### ISSUE THREAD

**Issue by wally2511** [cyberman54/ESP32-Paxcounter#811]
Hello,

I cannot get paxcounter to compile and get the following errors.

--------------------------------------------------------------------------
Library Manager: Installing bitbank2/OneBitDisplay @ ^1.10.0
**Warning! Could not find the package with 'bitbank2/OneBitDisplay @ ^1.10.0' requirements for your system 'windows_amd64'**
Library Manager: Installing bitbank2/BitBang_I2C @ ^2.1.3
**Warning! Could not find the package with 'bitbank2/BitBang_I2C @ ^2.1.3' requirements for your system 'windows_amd64'**
Found 50 compatible libraries
Scanning dependencies...

--------------------------------------------------------------------------

PlatformIO - 5.1.1
Visual studio code Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z (3 wks ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by cyberman54** [comment]
Fixed. Thank you for reporting this bug.
(seems something went wrong with that library properties).
