### ISSUE TITLE
Firmware for:  Modle: lora32 t3_v1.6 20180606

### ISSUE THREAD

**Issue by sp00ck** [cyberman54/ESP32-Paxcounter#826]
Where is firmware for my device? What I must to do next after install firmware? (tutorial is behing paywall)

**Comment by cyberman54** [comment]
Read the readme.md, that's why this file is named readme.

You need ttgov21new.h

**Comment by sp00ck** [comment]
please make a firmware for people who dont know how compiling

**Comment by cyberman54** [comment]
No. This is Github, a developer platform. So go and develop!

**Comment by sp00ck** [comment]
ok, i use disaster radio
