### ISSUE TITLE
Payload send cycle has no effect

### ISSUE THREAD

**Issue by wally2511** [cyberman54/ESP32-Paxcounter#828]
I've tried setting the send cycle using remote commands  (0A 96) and locally via the SENDCYLCE variable (followed by NVRAM flush/version increment). It seems to have no effect on the transmission interval. I'm seeing payloads as often as every 40 seconds.

Any thoughts?

![image](https://user-images.githubusercontent.com/29945084/130919232-7845eee6-d1b0-4443-9556-79cff015aff1.png)

**Comment by cyberman54** [comment]
I verified it, this was indeed a bug which came in with new libpax api, which used uint16_t  for millisecond sendcycle value. What happened is:

0x0a 0x96 -> 0x96 / 2 send cycle secs = 300 seconds = 300000 milliseconds

300000 = 0x493e0, casted to uint16_t this value is cropped to 0x93e0 = 37856 ms = 38 secs, and this is the cycle time you see.

The bugfix switches the libpax api from millseconds to seconds, this should now work as expected.

**Comment by wally2511** [comment]
I pulled the latest version and tested it today. The send cycle is working
perfectly. 👌
