### ISSUE TITLE
Buy paxcounter amazon but Display is reverse,  how to solve?

### ISSUE THREAD

**Issue by opabert** [cyberman54/ESP32-Paxcounter#837]
Hello all,

I buy a paxcounter TTGo from amazon, but the display is flipt and to read display the antenna pointed to below.  Like ask if possible step by step instructions for dummys how to solve display flip?  Or a ready made file to upload to TTGo board using USB?  
Thank you for any advice

**Comment by cyberman54** [comment]
You set
`#define MY_DISPLAY_FLIP  1` 
in the board's hal file (/src/hal), then rebuild and upload the software.

Since this is not an issue, please use discussions tab if you need further how to help.
