### ISSUE TITLE
Bootloop with ttgo_lora32_v21new

### ISSUE THREAD

**Issue by hekopath** [cyberman54/ESP32-Paxcounter#876]
I had a build problem for another project and used paxcounter to cross check the issue:
[https://github.com/lnlp/LMIC-node/issues/45](https://github.com/lnlp/LMIC-node/issues/45)

Currently there seems to be an issue with specific version of the TTGO Lora32 v21 (T3_1.6) boards.

As workaround the espressif framework can be used in a specific version.
Line 57 of platformio.ini can be changed to:
platform_espressif32 = espressif32@4.2.0
to successfully upload and run  the project.

If anyone can add useful information to fix the problems, you are most welcome!

**Comment by cyberman54** [comment]
I can't reproduce this with a  TTGO Lora32 v21 (T3_1.6) board, please post serial console monitor log here.
Generally, if you run in a bootloop, try to clear the NVRAM before uploading a fresh build:
`pio run -t erase`

You may also check the current v3.2.2 which is based on platformio-espressif 5.0.0.
