### ISSUE TITLE
Add support for reporting over the Helium network

### ISSUE THREAD

**Issue by DeflateAwning** [cyberman54/ESP32-Paxcounter#878]

**Comment by cyberman54** [comment]
Paxcounter is based in LMIC stack which is LoRaWAN 1.0.3 compliant. Thus, it can be used with every LoRaWAN network which is supporting this standard. Check with your network provider.

**Comment by cyberman54** [comment]
PS: i tested to registrate a paxcounter in Helium network. Worked as expected. But burns your $HNT wallet pretty fast since it reports all 60 seconds...

**Comment by DeflateAwning** [comment]
I'm wondering if you'd be able to share the tutorial or something? I think there might be a good opportunity to add a tutorial or explanation to this Git repo for anyone looking to get started!

**Comment by cyberman54** [comment]
it's just registrating a lorawan device in a lorawan network. Nothing special here, just enter keys and go. A tutorial would be just about lorawan basics. There are some, so why reinvent this wheel here again?
