### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by FrankHovis** [cyberman54/ESP32-Paxcounter#929]
PlatformIO gives this error:

Can not remove temporary directory `D:\ESP32-Paxcounter-master\.pio\build`. Please remove it manually to avoid build issues

 *  The terminal process "C:\Users\pauls\.platformio\penv\Scripts\platformio.exe 'run', '--environment', 'ci'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by cyberman54** [comment]
It seems you are trying to run the wrong environment. Use -e usb. Or just press platformio build button in the IDE.
