### ISSUE TITLE
Getting issue when trying to upload onto TBeamV1.1

### ISSUE THREAD

**Issue by aero-oli** [cyberman54/ESP32-Paxcounter#937]
<img width="936" alt="image" src="https://user-images.githubusercontent.com/73533343/216727880-05baf31e-6728-445c-ac8d-2b913d7fe02d.png">

**Comment by cyberman54** [comment]
As you can see from github action workflow, the current code compiles on all platforms.
Thus, it will be a local toolchain problem on your pc.
Check that you have current versions of all libs and platformio installed.
Or reinstall platformio and all libs.
