### ISSUE TITLE
Counting unique people with more than one pax counter? 

### ISSUE THREAD

**Issue by ClemensGruber** [cyberman54/ESP32-Paxcounter#972]
I try to count people on a larger venue at public events. So we have an old freight railway station with open air areas before and behind the former station. One pax counter will not count all people in the open area, the building and behind the building. 

Is it possible to combine two or more pax counter to cover a larger area? I fear not, because in this case counter must interchange the (anonymized) MAC addresses. I have seen that pax counters can be synchronized by time to measure the same time but as I understand it, the two (or more) counter will count people twice in case the measuring radii of each device overlapping. 

Any hint to deal with this issue? On.y count strong signals to have less overlapping?

**Comment by cyberman54** [comment]
This seems not an issue, but a feature request. Thus, i close this here.
For further questions or discussion, please move to discussion tab.

Paxcounter project intentionally does not track devices. So there is intentionally no feature in this code to track devices over a fleet of paxcounters.
