### ISSUE TITLE
Counter mode cyclic and cumulative in parallel? 

### ISSUE THREAD

**Issue by ClemensGruber** [cyberman54/ESP32-Paxcounter#973]
You can define by `COUNTERMODE` ([line 22 in paxcounter[_orig].conf](https://github.com/cyberman54/ESP32-Paxcounter/blob/5df47a171761a8c2a22e1af88f347d5ee2e782c5/src/paxcounter_orig.conf#LL22C1-L22C94))

`#define COUNTERMODE  0       // 0=cyclic, 1=cumulative, 2=cyclic confirmed`

that the _counter mode_ is `cyclic` vs. `cumulative`, that means counting 

(a) how much people are _current_ arround vs. 
(b) how much (unique) people were arround in x hours / days / since restart (?)

Is it possible to count current people `COUNTERMODE  0  // 0=cyclic` **and in parallel** how much unique people were around e.g. the last day? That's `COUNTERMODE  1  // 1=cumulative` resetted every day at 00:00 h or 04:00 h (for a long after midnight lasting event)? 

Or is the only way to get this data setting up two physical pax counter with different configurations? :(

**Comment by cyberman54** [comment]
See documentation:
https://cyberman54.github.io/ESP32-Paxcounter/remotecontrol/#0x02-set-counter-mode

In cumulative mode, you can reset the counter by rcommand 02 00 02 01.
Cumulative mode is useful to measure new arrivals, e.g. at events. Typically you see a steep curve at the beginning of an event. The curve flattenes when the arrivals decrease. This can be useful e.g. to adjust opening entrance doors, number of cash desks, etc.

This is not an issue, thus i close this. If you need further discussion, please move to discussions tab.
