### ISSUE TITLE
ttgov21new.h whant the 433mhz settings

### ISSUE THREAD

**Issue by uglurass** [cyberman54/ESP32-Paxcounter#992]
TTGO21NEW 1.6.1 
I got that board in 433mhz any suggestion how i add that in lora settings? eu433 just gives me error because there is not settings for it.

**Comment by cyberman54** [comment]
Paxcounter software is based on LMIC lorawan library. Im am sorry, but there is no 433 MHz support in LMIC so far. It is possible to get this working by patching the lmic library, see this [how-to](https://github.com/mcci-catena/arduino-lmic/issues/96).
